#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
levels:
    path: /levels
    controller:   App\Controller\WebsiteLevelsListController::index